In [2]:
from nltk.tokenize import word_tokenize
from collections import Counter
import collections
import sys
import MeCab
import re
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [ ]:
 # carmen # akai_heya# meijinden # at_a_railway_station

In [3]:
 corpus = ['This is the first document.','This document is the second document.','And this is the third one.','Is this the first document?',]
 vectorizer = CountVectorizer()
 matrix = vectorizer.fit_transform(corpus)

In [4]:
 print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [5]:
print(vectorizer.vocabulary_)

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}


In [6]:
tagger = MeCab.Tagger('-Owakati')    # 品詞情報が不要の場合
def tokenize(text):
    token_list = tagger.parse(text).split()
    return token_list

corpus = ['これは最初の文書です。','この文書は２番目の文書です。','そしてこれは3番目のものです。','これは最初の文書ですか？',]
vectorizer = CountVectorizer(analyzer=tokenize)
matrix = vectorizer.fit_transform(corpus)

In [7]:
print(vectorizer.get_feature_names())

['3', '。', 'か', 'この', 'これ', 'そして', 'です', 'の', 'は', 'もの', '文書', '最初', '番目', '２', '？']


In [8]:
print(matrix.toarray())

[[0 1 0 0 1 0 1 1 1 0 1 1 0 0 0]
 [0 1 0 1 0 0 1 1 1 0 2 0 1 1 0]
 [1 1 0 0 1 1 1 1 1 1 0 0 1 0 0]
 [0 0 1 0 1 0 1 1 1 0 1 1 0 0 1]]


In [9]:
tfidf = TfidfTransformer()
tfidf_matrix = tfidf.fit_transform(matrix)
np.set_printoptions(precision=2) 
print(tfidf_matrix.toarray())

[[ 0.    0.39  0.    0.    0.39  0.    0.32  0.32  0.32  0.    0.39  0.48
   0.    0.    0.  ]
 [ 0.    0.27  0.    0.43  0.    0.    0.22  0.22  0.22  0.    0.55  0.
   0.34  0.43  0.  ]
 [ 0.44  0.28  0.    0.    0.28  0.44  0.23  0.23  0.23  0.44  0.    0.
   0.34  0.    0.  ]
 [ 0.    0.    0.48  0.    0.31  0.    0.25  0.25  0.25  0.    0.31  0.38
   0.    0.    0.48]]


In [10]:
name_list = np.array(vectorizer.get_feature_names())
population = np.array(matrix.toarray())
indices = np.argsort(population)

In [25]:

print(name_list[indices[::-1]])
print(name_list[indices[::-1,0:9]])

[['3' '。' 'この' 'そして' 'もの' '番目' '２' 'か' 'これ' 'です' 'の' 'は' '文書' '最初' '？']
 ['か' 'この' '文書' '最初' '２' '？' '3' '。' 'これ' 'そして' 'です' 'の' 'は' 'もの' '番目']
 ['3' 'か' 'これ' 'そして' 'もの' '最初' '？' '。' 'この' 'です' 'の' 'は' '番目' '２' '文書']
 ['3' 'か' 'この' 'そして' 'もの' '番目' '２' '？' '。' 'これ' 'です' 'の' 'は' '文書' '最初']]
[['3' '。' 'この' 'そして' 'もの' '番目' '２' 'か' 'これ']
 ['か' 'この' '文書' '最初' '２' '？' '3' '。' 'これ']
 ['3' 'か' 'これ' 'そして' 'もの' '最初' '？' '。' 'この']
 ['3' 'か' 'この' 'そして' 'もの' '番目' '２' '？' '。']]


In [16]:
 print(name_list[indices])     

[['3' 'か' 'この' 'そして' 'もの' '番目' '２' '？' '。' 'これ' 'です' 'の' 'は' '文書' '最初']
 ['3' 'か' 'これ' 'そして' 'もの' '最初' '？' '。' 'この' 'です' 'の' 'は' '番目' '２' '文書']
 ['か' 'この' '文書' '最初' '２' '？' '3' '。' 'これ' 'そして' 'です' 'の' 'は' 'もの' '番目']
 ['3' '。' 'この' 'そして' 'もの' '番目' '２' 'か' 'これ' 'です' 'の' 'は' '文書' '最初' '？']] 5


In [13]:
print(indices)

[[ 0  2  3  5  9 12 13 14  1  4  6  7  8 10 11]
 [ 0  2  4  5  9 11 14  1  3  6  7  8 12 13 10]
 [ 2  3 10 11 13 14  0  1  4  5  6  7  8  9 12]
 [ 0  1  3  5  9 12 13  2  4  6  7  8 10 11 14]]
